const translations = {
  ko: {
                        kwFrontend: '#프론트엔드',
    kwPhoto: '#감성사진',
    kwCafe: '#카페투어',
    kwOotd: 'OOTD',
    kwPortfolio: '포트폴리오',
    kwAi: 'AI 활용법',
kwFrontend: '#프론트엔드',
    kwPhoto: '#감성사진',
    kwCafe: '#카페투어',
    kwOotd: 'OOTD',
    kwPortfolio: '포트폴리오',
    kwAi: 'AI 활용법',
edited: ' (수정됨)',
    viewReplies: '답글 {n}개 보기',
    hideRepliesNum: '답글 {n}개 숨기기',
colorSelect: '색상 선택',
    saturation: '채도',
    brightness: '명도',
    enterContentEllipsis: '내용을 입력하세요...',
    registerBtn2: '등록',
    mediaAttachFailed: '미디어 첨부 실패',
    enterLinkUrl: '링크 URL을 입력하세요:',
    fontSize: '글자 크기',
    fontFamily: '폰트',
    fontColor: '글자 색상',
    bold: '굵게',
    italic: '기울임',
    underline: '밑줄',
    strikethrough: '취소선',
    alignLeft: '왼쪽 정렬',
    alignCenter: '가운데 정렬',
    alignRight: '오른쪽 정렬',
    alignJustify: '양쪽 정렬',
    insertLink: '링크 삽입',
    attachMedia: '미디어/파일 첨부',
    timeJustNow: '방금',
    timeMinsAgo: '{m}분 전',
    timeHoursAgo: '{h}시간 전',
    timeDaysAgo: '{d}일 전',
    timeWeeksAgo: '{w}주 전',
    timeDate: '{y}년 {m}월 {d}일',
    confirmBtn: '확인',
    cancelBtn: '취소',
    selectBtn: '선택',
restWalk: '쉼터 산책',
    coastTour: '연안 관광',
    underwaterExplore: '수중 탐사',
    titlePlaceholder: '제목을 입력하세요',
    changeProfilePhoto: '프로필 사진 변경',
    imageProcessFail: '이미지 처리에 실패했습니다.',
    removeProfilePhoto: '프로필 제거',
    draftSaved: '임시저장 되었습니다.',
    profileUpdated: '프로필이 업데이트되었습니다.',
    copyLink: '링크 복사',
    shareComingSoon: '공유 기능 준비중',
    commentAdded: '댓글이 작성되었습니다',
    uploadImageRequired: '이미지를 업로드해주세요',
    enterContent: '내용을 입력하세요',
    uploadImageFailed: '이미지 업로드 실패',
    finish: '완료',
    saveDraft: '임시저장',
    imageRequired: '이미지를 필수로 업로드해야 합니다.',
    shellCreated: '셸이 완성되었습니다.',
    suggestionsForYou: '회원님을 위한 추천',
    seeAll: '모두 보기',
    switchAccount: '계정 전환',
    following: '팔로잉',
    follow: '팔로우',
    options: '옵션',
    addExistingAccount: '기존 계정 추가',
    footerLinks: '소개 · 도움말 · 홍보 센터 · API · 채용 정보 · 개인정보처리방침 · 약관 · 위치 · 언어 · Meta Verified',
    searchPlaceholder: '검색',
    noSearchResults: '검색 결과가 없습니다.',
    noComments: '아직 댓글이 없습니다.',
    firstComment: '가장 먼저 댓글을 남겨보세요.',
    leaveReply: '답글 남기기...',
    replyBtnText: '답글',
    replyAdded: '답글이 작성되었습니다',
    editComplete: '수정 완료',
    viewMoreReplies: '더 많은 답글 보기',
    hideReplies: '답글 숨기기',
    feedError: '오류가 발생했습니다:',
    postError: '오류가 발생했습니다:',
more: '더보기',
    home: '홈', explore: '탐색', profile: '프로필', create: '만들기', settings: '설정', logout: '로그아웃',
    newReef: '새 리프 만들기', newShell: '새 셸 만들기', uploadPhoto: '사진 업로드', addText: '텍스트 추가',
    finishUpload: '완성 및 업로드', editProfile: '프로필 편집', security: '계정 보안', theme: '테마', language: '언어',
    nickname: '닉네임', bio: '소개', website: '웹사이트', saveChanges: '변경사항 저장',
    languageSelectorDesc: '앱의 표시 언어를 설정하세요.', login: '로그인', signup: '회원가입',
    welcomeBanner: 'koral에 오신 것을 환영합니다', welcomeSub: '개발자를 위한 마크다운 SNS. 멋진 코드와 일상을 공유하세요.',
    signupBanner: 'koral 회원가입', signupSub: '개발자들의 공간에 합류하세요. 새로운 아이디어와 코드가 기다립니다.',
    placeholderSearch: '검색어를 입력하세요...', recentSearches: '최근 검색어', recommendedSearches: '추천 검색어',
    clearAll: '전체 삭제', searchResultsFor: '검색 결과', noRecentSearches: '최근 검색 기록이 없습니다.',
    comments: '댓글', addComment: '댓글 남기기...', registerBtn: '등록', replyBtn: '답글 달기',
    writeSomething: '이야기를 나누어 보세요...', reefUpload: '리프 올리기', edit: '수정', delete: '삭제', report: '신고',
    linkCopied: '링크가 복사되었습니다.', loginTitle: '로그인', signupTitle: '새 계정 만들기',
    password: '비밀번호', handleOrEmail: '핸들 또는 이메일', haveAccount: '계정이 있으신가요?', noAccount: '계정이 없으신가요?',
    agreeTerms: '가입하면 koral의 약관, 데이터 정책 및 쿠키 정책에 동의하게 됩니다.', acceptTerms: '약관',
    addAvatar: '프로필 사진 추가', handlePlaceholder: '핸들 입력',
    myShell: '내 셸', loginRequired: '로그인이 필요합니다.', emailPlaceholder: '이메일 주소', nicknamePlaceholder: '닉네임',
    
    // Extended keys
    noReefs: '아직 리프가 없습니다.',
    noReefsSub: '첫 번째 리프를 작성하거나 다른 사용자를 팔로우해 보세요.',
    userNotFound: '사용자를 찾을 수 없습니다.',
    userNotFoundSub: '링크가 잘못되었거나 삭제된 계정입니다.',
    following: '팔로잉',
    follow: '팔로우',
    message: '메시지',
    messageFeatureReady: '메시지 기능 준비중',
    statReefs: ' 리프',
    statFollowers: ' 팔로워',
    statFollowing: ' 팔로우',
    noReefsTitle: '리프 없음',
    noSavedReefsTitle: '저장된 리프 없음',
    commentsTitle: '댓글',
    reefCreated: '리프가 생성되었습니다.',
    createTitle: '만들기',
    createQuestion: '어떤 콘텐츠를 만드시겠어요?',
    reefLabel: '리프 (Reef)',
    reefDesc: '긴 글과 사진을 공유하세요.',
    shellLabel: '셸 (Shell)',
    shellDesc: '24시간 후 사라지는 이야기.',
    devNoteLabel: '개발 노트',
    devNoteDesc: '추후 업데이트 예정',
    featureReadyInfo: '준비 중인 기능입니다.',
    editPost: '수정 완료',
    editSuccess: '수정되었습니다.',
    deleteConfirm: '정말 이 리프를 삭제하시겠습니까?',
    deleteSuccess: '삭제되었습니다.',
    reportSuccess: '신고가 접수되었습니다.',
    themeSelectorDesc: '앱의 화면 모드를 설정하세요.',
    themeSystem: '시스템 설정',
    themeLight: '라이트 모드',
    themeDark: '다크 모드',
    themeSystemDesc: '기기 설정에 맞춤',
    themeLightDesc: '밝은 테마',
    themeDarkDesc: '어두운 테마'
  },
  en: {
                        kwFrontend: '#Frontend',
    kwPhoto: '#AestheticPhoto',
    kwCafe: '#CafeTour',
    kwOotd: 'OOTD',
    kwPortfolio: 'Portfolio',
    kwAi: 'AI Tips',
kwFrontend: '#Frontend',
    kwPhoto: '#AestheticPhoto',
    kwCafe: '#CafeTour',
    kwOotd: 'OOTD',
    kwPortfolio: 'Portfolio',
    kwAi: 'AI Tips',
edited: ' (edited)',
    viewReplies: 'View {n} replies',
    hideRepliesNum: 'Hide {n} replies',
colorSelect: 'Select Color',
    saturation: 'Saturation',
    brightness: 'Brightness',
    enterContentEllipsis: 'Enter content...',
    registerBtn2: 'Submit',
    mediaAttachFailed: 'Failed to attach media',
    enterLinkUrl: 'Enter link URL:',
    fontSize: 'Font Size',
    fontFamily: 'Font',
    fontColor: 'Font Color',
    bold: 'Bold',
    italic: 'Italic',
    underline: 'Underline',
    strikethrough: 'Strikethrough',
    alignLeft: 'Align Left',
    alignCenter: 'Align Center',
    alignRight: 'Align Right',
    alignJustify: 'Justify',
    insertLink: 'Insert Link',
    attachMedia: 'Attach Media/File',
    timeJustNow: 'Just now',
    timeMinsAgo: '{m}m ago',
    timeHoursAgo: '{h}h ago',
    timeDaysAgo: '{d}d ago',
    timeWeeksAgo: '{w}w ago',
    timeDate: '{y}-{m}-{d}',
    confirmBtn: 'Confirm',
    cancelBtn: 'Cancel',
    selectBtn: 'Select',
restWalk: 'Rest Walk',
    coastTour: 'Coast Tour',
    underwaterExplore: 'Underwater Explore',
    titlePlaceholder: 'Enter title',
    changeProfilePhoto: 'Change Profile Photo',
    imageProcessFail: 'Image processing failed.',
    removeProfilePhoto: 'Remove Profile',
    draftSaved: 'Draft saved.',
    profileUpdated: 'Profile updated successfully.',
    copyLink: 'Copy Link',
    shareComingSoon: 'Share feature coming soon',
    commentAdded: 'Comment added successfully.',
    uploadImageRequired: 'Please upload an image',
    enterContent: 'Please enter content',
    uploadImageFailed: 'Failed to upload image',
    finish: 'Finish',
    saveDraft: 'Save Draft',
    imageRequired: 'You must upload an image.',
    shellCreated: 'Shell created successfully.',
    suggestionsForYou: 'Suggestions for you',
    seeAll: 'See All',
    switchAccount: 'Switch Account',
    following: 'Following',
    follow: 'Follow',
    options: 'Options',
    addExistingAccount: 'Add Existing Account',
    footerLinks: 'About · Help · Press · API · Jobs · Privacy · Terms · Locations · Language · Meta Verified',
    searchPlaceholder: 'Search',
    noSearchResults: 'No search results found.',
    noComments: 'No comments yet.',
    firstComment: 'Be the first to comment.',
    leaveReply: 'Leave a reply...',
    replyBtnText: 'Reply',
    replyAdded: 'Reply added successfully.',
    editComplete: 'Edit Complete',
    viewMoreReplies: 'View more replies',
    hideReplies: 'Hide replies',
    feedError: 'An error occurred:',
    postError: 'An error occurred:',
more: 'More',
    home: 'Home', explore: 'Explore', profile: 'Profile', create: 'Create', settings: 'Settings', logout: 'Logout',
    newReef: 'Create New Reef', newShell: 'Create New Shell', uploadPhoto: 'Upload Photo', addText: 'Add Text',
    finishUpload: 'Finish & Upload', editProfile: 'Edit Profile', security: 'Security', theme: 'Theme', language: 'Language',
    nickname: 'Nickname', bio: 'Bio', website: 'Website', saveChanges: 'Save Changes',
    languageSelectorDesc: 'Select the display language of the app.', login: 'Login', signup: 'Sign Up',
    welcomeBanner: 'Welcome to koral', welcomeSub: 'Markdown SNS for developers. Share your awesome code and daily life.',
    signupBanner: 'Join koral', signupSub: 'Join the space for developers. New ideas and code await you.',
    placeholderSearch: 'Type search keywords...', recentSearches: 'Recent Searches', recommendedSearches: 'Recommended',
    clearAll: 'Clear All', searchResultsFor: 'Search results for', noRecentSearches: 'No recent searches.',
    comments: 'Comments', addComment: 'Leave a comment...', registerBtn: 'Post', replyBtn: 'Reply',
    writeSomething: 'Share your thoughts...', reefUpload: 'Publish Reef', edit: 'Edit', delete: 'Delete', report: 'Report',
    linkCopied: 'Link copied to clipboard.', loginTitle: 'Log In', signupTitle: 'Create New Account',
    password: 'Password', handleOrEmail: 'Handle or Email', haveAccount: 'Already have an account?', noAccount: "Don't have an account?",
    agreeTerms: 'By signing up, you agree to our Terms, Data Policy and Cookies Policy.', acceptTerms: 'Terms',
    addAvatar: 'Add Profile Photo', handlePlaceholder: 'Enter handle',
    myShell: 'My Shell', loginRequired: 'Login is required.', emailPlaceholder: 'Email Address', nicknamePlaceholder: 'Nickname',
    
    // Extended keys
    noReefs: 'No 里夫 Yet.',
    noReefsSub: 'Publish your first reef or follow other users to fill your feed.',
    userNotFound: 'User Not Found',
    userNotFoundSub: 'The link might be broken or the account has been deleted.',
    following: 'Following',
    follow: 'Follow',
    message: 'Message',
    messageFeatureReady: 'Messaging is coming soon.',
    statReefs: ' 里夫',
    statFollowers: ' Followers',
    statFollowing: ' Following',
    noReefsTitle: 'No 里夫',
    noSavedReefsTitle: 'No Saved 里夫',
    commentsTitle: 'Comments',
    reefCreated: 'Reef created successfully.',
    createTitle: 'Create',
    createQuestion: 'What kind of content would you like to make?',
    reefLabel: '里夫 (Reef)',
    reefDesc: 'Share long posts and photos.',
    shellLabel: '雪尔 (Shell)',
    shellDesc: 'Stories that disappear after 24 hours.',
    devNoteLabel: 'Dev Note',
    devNoteDesc: 'Coming soon',
    featureReadyInfo: 'This feature is coming soon.',
    editPost: 'Save Edits',
    editSuccess: 'Edited successfully.',
    deleteConfirm: 'Are you sure you want to delete this Reef?',
    deleteSuccess: 'Deleted successfully.',
    reportSuccess: 'Report submitted successfully.',
    themeSelectorDesc: 'Configure the display mode of the app.',
    themeSystem: 'System Setting',
    themeLight: 'Light Mode',
    themeDark: 'Dark Mode',
    themeSystemDesc: 'Matches system configuration',
    themeLightDesc: 'Bright theme',
    themeDarkDesc: 'Dark theme'
  },
  ja: {
                        kwFrontend: '#フロントエンド',
    kwPhoto: '#エモい写真',
    kwCafe: '#カフェ巡り',
    kwOotd: 'OOTD',
    kwPortfolio: 'ポートフォリオ',
    kwAi: 'AI活用法',
kwFrontend: '#フロントエンド',
    kwPhoto: '#エモい写真',
    kwCafe: '#カフェ巡り',
    kwOotd: 'OOTD',
    kwPortfolio: 'ポートフォリオ',
    kwAi: 'AI活用法',
edited: ' (編集済み)',
    viewReplies: '{n}件の返信を見る',
    hideRepliesNum: '{n}件の返信を隠す',
colorSelect: '色を選択',
    saturation: '彩度',
    brightness: '明度',
    enterContentEllipsis: '内容を入力してください...',
    registerBtn2: '登録',
    mediaAttachFailed: 'メディア添付失敗',
    enterLinkUrl: 'リンクURLを入力してください:',
    fontSize: '文字サイズ',
    fontFamily: 'フォント',
    fontColor: '文字色',
    bold: '太字',
    italic: '斜体',
    underline: '下線',
    strikethrough: '取り消し線',
    alignLeft: '左揃え',
    alignCenter: '中央揃え',
    alignRight: '右揃え',
    alignJustify: '両端揃え',
    insertLink: 'リンク挿入',
    attachMedia: 'メディア/ファイル添付',
    timeJustNow: 'たった今',
    timeMinsAgo: '{m}分前',
    timeHoursAgo: '{h}時間前',
    timeDaysAgo: '{d}日前',
    timeWeeksAgo: '{w}週間前',
    timeDate: '{y}年{m}月{d}日',
    confirmBtn: '確認',
    cancelBtn: 'キャンセル',
    selectBtn: '選択',
restWalk: '休憩散歩',
    coastTour: '沿岸観光',
    underwaterExplore: '水中探査',
    titlePlaceholder: 'タイトルを入力',
    changeProfilePhoto: 'プロフィール写真変更',
    imageProcessFail: '画像処理に失敗しました。',
    removeProfilePhoto: 'プロフィール削除',
    draftSaved: '下書き保存されました。',
    profileUpdated: 'プロフィールが更新されました。',
    copyLink: 'リンクコピー',
    shareComingSoon: '共有機能準備中',
    commentAdded: 'コメントが追加されました。',
    uploadImageRequired: '画像をアップロードしてください',
    enterContent: '内容を入力してください',
    uploadImageFailed: '画像アップロード失敗',
    finish: '完了',
    saveDraft: '下書き保存',
    imageRequired: '画像は必須です。',
    shellCreated: 'シェルが作成されました。',
    suggestionsForYou: 'おすすめのユーザー',
    seeAll: 'すべて見る',
    switchAccount: 'アカウント切り替え',
    following: 'フォロー中',
    follow: 'フォロー',
    options: 'オプション',
    addExistingAccount: '既存のアカウントを追加',
    footerLinks: '基本情報 · ヘルプ · プレス · API · 求人 · プライバシー · 規約 · 位置 · 言語 · Meta Verified',
    searchPlaceholder: '検索',
    noSearchResults: '検索結果がありません。',
    noComments: 'まだコメントがありません。',
    firstComment: '最初のコメントを残してみましょう。',
    leaveReply: '返信を残す...',
    replyBtnText: '返信',
    replyAdded: '返信が作成されました',
    editComplete: '修正完了',
    viewMoreReplies: '他の返信を見る',
    hideReplies: '返信を隠す',
    feedError: 'エラーが発生しました:',
    postError: 'エラーが発生しました:',
more: 'もっと見る',
    home: 'ホーム', explore: '検索', profile: 'プロフィール', create: '作成', settings: '設定', logout: 'ログアウト',
    newReef: '新規リーフ作成', newShell: '新規シェル作成', uploadPhoto: '写真アップロード', addText: 'テキスト追加',
    finishUpload: '完成してアップロード', editProfile: 'プロフィール編集', security: 'セキュリティ', theme: 'テーマ', language: '言語',
    nickname: 'ニックネーム', bio: '自己紹介', website: 'ウェブサイト', saveChanges: '変更を保存',
    languageSelectorDesc: 'アプリの表示言語を設定します。', login: 'ログイン', signup: '会員登録',
    welcomeBanner: 'koralへようこそ', welcomeSub: '開発者のためのマークダウンSNS。コードと日常を共有しましょう。',
    signupBanner: 'koral 会員登録', signupSub: '開発者のための空間に参加しましょう。新しいアイデアとコードが待っています。',
    placeholderSearch: '検索ワードを入力...', recentSearches: '最近の検索', recommendedSearches: 'おすすめ',
    clearAll: 'すべて削除', searchResultsFor: 'の検索結果', noRecentSearches: '最近の検索履歴はありません。',
    comments: 'コメント', addComment: 'コメントを残す...', registerBtn: '登録', replyBtn: '返信',
    writeSomething: '考えを共有しましょう...', reefUpload: 'リーフを投稿', edit: '編集', delete: '削除', report: '報告',
    linkCopied: 'リンクがコピーされました。', loginTitle: 'ログイン', signupTitle: '新規アカウント作成',
    password: 'パスワード', handleOrEmail: 'ハンドルまたはメールアドレス', haveAccount: 'すでにアカウントをお持ちですか？', noAccount: 'アカウントをお持ちでないですか？',
    agreeTerms: '登録すると、koralの利用規約、データに関するポリシー、Cookieに関するポリシーに同意したことになります。', acceptTerms: '利用規約',
    addAvatar: 'プロフィール写真を追加', handlePlaceholder: 'ハンドルを入力',
    myShell: 'マイシェル', loginRequired: 'ログインが必要です。', emailPlaceholder: 'メールアドレス', nicknamePlaceholder: 'ニックネーム',
    
    // Extended keys
    noReefs: 'リーフがまだありません。',
    noReefsSub: '最初のリーフを投稿するか、他のユーザーをフォローしてみましょう。',
    userNotFound: 'ユーザーが見つかりません。',
    userNotFoundSub: 'リンクが正しくないか、削除されたアカウントです。',
    following: 'フォロー中',
    follow: 'フォロー',
    message: 'メッセージ',
    messageFeatureReady: 'メッセージ機能は準備中です。',
    statReefs: ' リーフ',
    statFollowers: ' フォロワー',
    statFollowing: ' フォロー',
    noReefsTitle: 'リーフなし',
    noSavedReefsTitle: '保存されたリーフなし',
    commentsTitle: 'コメント',
    reefCreated: 'リーフが作成されました。',
    createTitle: '作成',
    createQuestion: 'どのようなコンテンツを作成しますか？',
    reefLabel: 'リーフ (Reef)',
    reefDesc: '長い文章と写真を共有しましょう。',
    shellLabel: 'シェル (Shell)',
    shellDesc: '24時間で消えるストーリー。',
    devNoteLabel: '開発ノート',
    devNoteDesc: '今後のアップデートで対応',
    featureReadyInfo: '準備中の機能です。',
    editPost: '編集完了',
    editSuccess: '編集されました。',
    deleteConfirm: '本当にこのリーフを削除しますか？',
    deleteSuccess: '削除されました。',
    reportSuccess: '報告が受け付けられました。',
    themeSelectorDesc: 'アプリの画面モードを設定します。',
    themeSystem: 'システム設定',
    themeLight: 'ライトモード',
    themeDark: 'ダークモード',
    themeSystemDesc: '端末の設定に合わせる',
    themeLightDesc: '明るいテーマ',
    themeDarkDesc: '暗いテーマ'
  },
  zh: {
                        kwFrontend: '#前端',
    kwPhoto: '#唯美照片',
    kwCafe: '#探店',
    kwOotd: 'OOTD',
    kwPortfolio: '作品集',
    kwAi: 'AI应用',
kwFrontend: '#前端',
    kwPhoto: '#唯美照片',
    kwCafe: '#探店',
    kwOotd: 'OOTD',
    kwPortfolio: '作品集',
    kwAi: 'AI应用',
edited: ' (已编辑)',
    viewReplies: '查看 {n} 条回复',
    hideRepliesNum: '隐藏 {n} 条回复',
colorSelect: '选择颜色',
    saturation: '饱和度',
    brightness: '亮度',
    enterContentEllipsis: '请输入内容...',
    registerBtn2: '提交',
    mediaAttachFailed: '媒体附件失败',
    enterLinkUrl: '输入链接网址:',
    fontSize: '字体大小',
    fontFamily: '字体',
    fontColor: '字体颜色',
    bold: '加粗',
    italic: '斜体',
    underline: '下划线',
    strikethrough: '删除线',
    alignLeft: '左对齐',
    alignCenter: '居中对齐',
    alignRight: '右对齐',
    alignJustify: '两端对齐',
    insertLink: '插入链接',
    attachMedia: '附加媒体/文件',
    timeJustNow: '刚刚',
    timeMinsAgo: '{m}分钟前',
    timeHoursAgo: '{h}小时前',
    timeDaysAgo: '{d}天前',
    timeWeeksAgo: '{w}周前',
    timeDate: '{y}年{m}月{d}日',
    confirmBtn: '确认',
    cancelBtn: '取消',
    selectBtn: '选择',
restWalk: '休憩散步',
    coastTour: '沿海观光',
    underwaterExplore: '水下探索',
    titlePlaceholder: '输入标题',
    changeProfilePhoto: '更改个人头像',
    imageProcessFail: '图片处理失败。',
    removeProfilePhoto: '移除头像',
    draftSaved: '已保存草稿。',
    profileUpdated: '个人资料已更新。',
    copyLink: '复制链接',
    shareComingSoon: '分享功能准备中',
    commentAdded: '评论已添加。',
    uploadImageRequired: '请上传图片',
    enterContent: '请输入内容',
    uploadImageFailed: '图片上传失败',
    finish: '完成',
    saveDraft: '保存草稿',
    imageRequired: '必须上传图片。',
    shellCreated: '雪尔已创建。',
    suggestionsForYou: '为您推荐',
    seeAll: '查看全部',
    switchAccount: '切换账号',
    following: '正在关注',
    follow: '关注',
    options: '选项',
    addExistingAccount: '添加已有账号',
    footerLinks: '关于 · 帮助 · 新闻 · API · 工作 · 隐私 · 条款 · 位置 · 语言 · Meta Verified',
    searchPlaceholder: '搜索',
    noSearchResults: '无搜索结果。',
    noComments: '暂无评论。',
    firstComment: '留下第一条评论吧。',
    leaveReply: '写下回复...',
    replyBtnText: '回复',
    replyAdded: '回复已添加',
    editComplete: '修改完成',
    viewMoreReplies: '查看更多回复',
    hideReplies: '隐藏回复',
    feedError: '发生错误:',
    postError: '发生错误:',
more: '更多',
    home: '首页', explore: '探索', profile: '个人主页', create: '创建', settings: '设置', logout: '退出登录',
    newReef: '新建里夫', newShell: '新建雪尔', uploadPhoto: '上传图片', addText: '添加文本',
    finishUpload: '完成并上传', editProfile: '编辑资料', security: '账号安全', theme: '主题', language: '语言',
    nickname: '昵称', bio: '个人简介', website: '网站', saveChanges: '保存更改',
    languageSelectorDesc: '设置应用的显示语言。', login: '登录', signup: '注册',
    welcomeBanner: '欢迎来到 koral', welcomeSub: '面向开发者的 Markdown 社交平台。分享您的代码与日常生活。',
    signupBanner: '注册 koral', signupSub: '加入开发者的专属空间。全新的创意与代码在等待着您。',
    placeholderSearch: '输入搜索关键词...', recentSearches: '最近搜索', recommendedSearches: '推荐搜索',
    clearAll: '清除全部', searchResultsFor: '的搜索结果', noRecentSearches: '暂无搜索记录。',
    comments: '评论', addComment: '留下一条评论...', registerBtn: '发布', replyBtn: '回复',
    writeSomething: '分享您的想法...', reefUpload: '发布里夫', edit: '编辑', delete: '删除', report: '举报',
    linkCopied: '链接已复制到剪贴板。', loginTitle: '登录', signupTitle: '创建新账号',
    password: '密码', handleOrEmail: '用户名或邮箱', haveAccount: '已有账号？', noAccount: '没有账号？',
    agreeTerms: '注册即表示您同意 koral 的服务条款、数据政策和 Cookie 政策。', acceptTerms: '条款',
    addAvatar: '添加头像', handlePlaceholder: '输入用户名',
    myShell: '我的雪尔', loginRequired: '需要登录。', emailPlaceholder: '电子邮箱', nicknamePlaceholder: '昵称',
    
    // Extended keys
    noReefs: '暂无里夫。',
    noReefsSub: '发布您的第一个里夫或关注其他用户。',
    userNotFound: '找不到用户',
    userNotFoundSub: '链接无效或账号已被删除。',
    following: '正在关注',
    follow: '关注',
    message: '私信',
    messageFeatureReady: '私信功能正在开发中。',
    statReefs: ' 里夫',
    statFollowers: ' 粉丝',
    statFollowing: ' 关注',
    noReefsTitle: '暂无里夫',
    noSavedReefsTitle: '暂无保存的里夫',
    commentsTitle: '评论',
    reefCreated: '里夫发布成功。',
    createTitle: '创建',
    createQuestion: '您想创建什么内容？',
    reefLabel: '里夫 (Reef)',
    reefDesc: '分享长文和图片。',
    shellLabel: '雪尔 (Shell)',
    shellDesc: '24小时后消失的故事。',
    devNoteLabel: '开发笔记',
    devNoteDesc: '敬请期待',
    featureReadyInfo: '此功能正在开发中。',
    editPost: '保存修改',
    editSuccess: '修改成功。',
    deleteConfirm: '确定要删除这个里夫吗？',
    deleteSuccess: '删除成功。',
    reportSuccess: '举报已受理。',
    themeSelectorDesc: '设置应用的显示模式。',
    themeSystem: '系统设置',
    themeLight: '浅色模式',
    themeDark: '深色模式',
    themeSystemDesc: '跟随系统配置',
    themeLightDesc: '明亮主题',
    themeDarkDesc: '暗黑主题'
  }
};

function t(key) {
  const currentLang = localStorage.getItem('koral_language') || 'ko';
  return translations[currentLang]?.[key] || translations['ko']?.[key] || key;
}
